config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'

  root to: 'tests#index'

  resources :gists, only: :create

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :result, only: %i[show update] do
    member do
      get :user_result
    end
  end

  namespace :admin do
    get '/gists', to: "gists#index"

    resources :badges, shallow: true

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_achievements, dependent: :destroy
  has_many :users, through: :user_achievements

  validates :file_name, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true

  scope :hidden_badges, ->(user) { where.not(id: user.badges) }
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def destroy
    @badge = Badge.find(params[:id])
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :file_name, :rule_type, :type_title, :param)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
    @hide_badges = @badges.hidden_badges(current_user)
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= octicon "#{badge.file_name}", class: "first test success" %></td>
  <td><%= link_to 'Delete', admin_badge_path(badge),
                  method: :delete,
                  data: { confirm: 'Do you want to delete this badge' } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <div class="select">
    <ul>
      <%= form.label :title %><br>
      <%= form.text_field :title, id: :badge_title %>
    </ul>

    <ul><p>Название брать с https://github.com/primer/octicons/tree/main/icons </p>
      <%= form.label :file_name %><br>
      <%= form.text_field :file_name, id: :badge_file_name %>
    </ul>

    <ul class=" rule">
      <%= form.label :rule_type %><br>
      <%= form.select :rule_type, BadgeService::RULES.keys, include_blank: 'Select' %>
    </ul>

    <ul class=" Params">
      <%= form.label :param %><br>
      <%= form.number_field :param, id: :badge_param %>
    </ul>
  </div>

  <div class="show category">
    Выберете ID Категории
    <table>
      <tr>
        <th>Id</th>
        <th>Title</th>
      </tr>
      <% Category.all.each do |category| %>
        <tr>
          <td><%= category.id %></td>
          <td><%= category.title %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="show tests">
    Выберете ID Теста
    <table>
      <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Level</th>
      </tr>
      <% Test.all.each do |test| %>
        <tr>
          <td><%= test.id %></td>
          <td><%= test.title %></td>
          <td><%= test.level %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/index.html.erb
<h1>User badges</h1>
<%=link_to 'New badge', new_admin_badge_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th>Action</th>
  </tr>
  <%= render @badges %>
</table>

<%= render 'shared/footer' %>

app/views/admin/badges/new.html.erb
<h1>Create new Badge</h1>

<%= render 'form' %>
<%= link_to 'Back', admin_tests_path %>