config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'

  root to: 'tests#index'

  resources :gists, only: :create

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :result, only: %i[show update] do
    member do
      get :user_result
    end
  end

  namespace :admin do
    get '/gists', to: "gists#index"

    resources :badges, shallow: true

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :title, presence: true
  validate :validate_quantity_of_answers, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_quantity_of_answers
    if question.answers.count >= 4
      errors.add(:base, :count, message: "The question must have from 1 to 4 questions")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_achievements, dependent: :destroy
  has_many :users, through: :user_achievements

  validates :file_name, presence: true, uniqueness: true
  validates :title, presence: true, uniqueness: true

  scope :hidden_badges, ->(user) { where.not(id: user.badges) }
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :destroy

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true
  before_validation :before_validation_set_next_question

  SUCCESS_RATIO = 0.85

  def completed?
    current_question.nil? || test_timer_end?
  end

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def successful?(result)
    check_quality(result) >= SUCCESS_RATIO
  end

  def current_question_number
    test.questions.order(:id).where('id < ?', current_question.id).size + 1
  end

  def check_quality(result)
    (result.correct_questions / test.questions.count.to_f) * 100
  end

  private

  def test_timer_end?
    return false if test.time_remain.nil?

    created_at + test.time_remain * 60 - Time.current <= 0
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    if new_record?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :questions, dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :users, through: :results

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10 }, allow_nil: true

  scope :user_tests, -> (level) { where(level: level) }
  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where level: 2..4 }
  scope :hard, -> { where level: 5..Float::INFINITY }
  scope :all_category_tests, -> (category_title) { joins(:category)
                                                     .where(categories: { title: category_title })
                                                     .order(title: :desc) }

  def self.list_all_category_test(category)
    all_category_tests(category).pluck(:title)
  end
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :confirmable,
         :validatable

  has_many :create_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :results, dependent: :destroy
  has_many :tests, through: :results
  has_many :gists, dependent: :destroy
  has_many :user_achievements, dependent: :destroy
  has_many :badges, through: :user_achievements

  validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "correct email" }

  def user_tests(level)
    tests.where(level: level)
  end

  def result(test)
    results.order(id: :desc).find_by(test_id: test.id)
  end
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = current_user.badges
    @hide_badges = @badges.hidden_badges(current_user)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def create
    @result = current_user.results.last
    result = GistQuestionService.new(@result.current_question).call

    if result.success?
      Gist.create!(url: result.url, question_id: @result.current_question.id, user_id: current_user.id)
      flash[:notice] = result.url
    else
      flash[:failure] = t('result.gists.create.failure')
    end

    redirect_to @result
  end
end

app/controllers/result_controller.rb
class ResultController < ApplicationController

  before_action :authenticate_user!
  before_action :set_result, only: %i[show update user_result]
  before_action :set_test, only: %i[user_result show update]

  def show; end

  def user_result; end

  def update
    @result.accept!(params[:answer_ids])

    if @result.completed?
      TestsMailer.completed_test(@result).deliver_now
      new_badge = BadgeService.new(@result).call

      if new_badge.success?
        flash[:notice] = "Поздравляю, вы получили новый значок"
      end

      redirect_to user_result_result_path(@result)
    else
      render :show
    end
  end

  private

  def set_result
    @result = Result.find(params[:id])
  end

  def set_test
    @test = Test.find(@result.test_id)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :authenticate_user!

  def index
    @tests = Test.all
  end

  def start
    @test = Test.find(params[:id])
    current_user.tests.push(@test)
    redirect_to current_user.result(@test)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header
    if @question.new_record?
      "Create new '#{@test.title}' Question"
    else
      "Edit '#{@question.test.title}' Question"
    end
  end

  def current_year
    Date.current.year
  end

  def github_url(author: , repo: , title:)
    link_to "#{title}", "https://github.com/#{author}/#{repo}"

  end
end

app/helpers/result_helper.rb
module ResultHelper
end

app/helpers/tests_helper.rb
module TestsHelper

  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class=" nav-admin title">TestGuru Admin Panel</span>

  <div class="nav-admin user">
    Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru|
    <%=link_to 'Gists', admin_gists_path %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Panel | TestGuru</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<%=render 'admin/nav' %>
<%=render 'shared/flash' %>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGuru</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
  <p class="nav user">
    <%= link_to "Welcome, #{ current_user.email}  Guru", root_path %></p>
  <p class="nav user"> <%= link_to "Log out", destroy_user_session_path, method: :delete%></p>
<% else %>
  <p class="nav user"><%= link_to 'Log in', sessions_new_path %> <%= link_to 'Registration', new_user_session_path %> </p>
<% end %>

<%=render 'shared/flash' %>

<%= yield %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? and resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: {resource_id: resource.id} do %>
    <h2>Errors detected:</h2>
    <h2><%= pluralize(resource.errors.count, 'error') %> detected </h2>
    <ul>
      <% resource.errors.full_messages.each do |messages| %>
        <li><%= messages %></li>
      <% end %>
    </ul>
  <%end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<h3><%= current_year %> Смирнов Николай</h3>

<p>Приложение для создания и прохождения тестов</p>
<p><%= github_url(author: 'mgoldm', repo: 'Test-guru', title: 'Test-guru') %></p>

<%= link_to 'Учебный проект в онлайн-школе Thinknetica', "https://thinknetica.com" %>