config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'

  root to: 'tests#index'

  resources :gists, only: :create

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :result, only: %i[show update] do
    member do
      get :user_result
    end
  end

  namespace :admin do
    get '/gists', to: "gists#index"

    resources :badges, shallow: true

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/admin/gists_controller.rb
class Admin::GistsController < Admin::BaseController
  def index
    @gists = Gist.all
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def create
    @result = current_user.results.last
    result = GistQuestionService.new(@result.current_question).call

    if result.success?
      Gist.create!(url: result.url, question_id: @result.current_question.id, user_id: current_user.id)
      flash[:notice] = result.url
    else
      flash[:failure] = t('result.gists.create.failure')
    end

    redirect_to @result
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/admin/gists/_gist.html.erb
<tr>
  <td><%= gist.url %></td>
  <td><%= gist.user.email %></td>
  <td><%=link_to "#{gist.question.title[0..15]}", admin_question_path(gist.question) %></td>
</tr>

app/views/admin/gists/index.html.erb
<h1>Gists</h1>

<table>
  <tr>
    <th>url</th>
    <th>User email</th>
    <th>Question body</th>
  </tr>
  <%= render @gists %>
</table>

<p><%=link_to 'Back', admin_tests_path %></p>
<%= render 'shared/footer' %>