config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: :gurus, path_name: { sign_in: :login, sign_out: :logout }

  get 'sessions/new'

  root to: 'tests#index'

  resources :gists, only: :create

  resources :badges, only: :index

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :result, only: %i[show update] do
    member do
      get :user_result
    end
  end

  namespace :admin do
    get '/gists', to: "gists#index"

    resources :badges, shallow: true

    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :title, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_question, only: %i[show destroy edit update]
  before_action :find_tests, only: %i[create new]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test)
    else
      redirect_to new_admin_test_question_path
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to root_path
  end

  private

  def rescue_with_question_not_found
    render plain: 'That question was not found'
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_tests
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:title)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header
    if @question.new_record?
      "Create new '#{@test.title}' Question"
    else
      "Edit '#{@question.test.title}' Question"
    end
  end

  def current_year
    Date.current.year
  end

  def github_url(author: , repo: , title:)
    link_to "#{title}", "https://github.com/#{author}/#{repo}"

  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>

  <%= render 'shared/errors', resource: @question %>
  <ul>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :question_title %>
  </ul>
  <p><%= form.submit %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= @question.title %></td>
  <h2>Answers</h2>
  <% link_to 'New Answer', new_admin_question_answer_path(@question) %>
  <ol>
    <%= render @question.answers %>
  </ol>

  <td><%= link_to 'Edit', edit_admin_question_path(@question) %></td>
  <td><%= link_to "Destroy", admin_question_path(@question),
                  method: :delete,
                  data: { confirm: "Do you want to delete this question?" } %></td>
  <td><%= link_to 'Back', admin_tests_path %></td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header %></h1>

<%= render 'form' %>

app/views/admin/questions/new.html.erb
<h1> <%= question_header %></h1>

<%= render 'form' %>'

app/views/admin/questions/show.html.erb
<%= render 'question' %>